name: Build and Deploy to AUR
on:
  create:
    tags:
      - v*

jobs:
  build-aur-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        with:
          pkgname: transmission-cli-git
          pkgbuild: ./PKGBUILD

      - name: Upload to Release Action
        uses: actions/upload-artifact@v4.6.2
        with:
          path: "./*/*.zst"

                
    
              
